### ISSUE TITLE
resource list convention

### ISSUE THREAD

**Issue by BriannaLind** [nasa/GEDI-Data-Resources#16]
it would be good for consistency if this followed how resources are described on other pages;
|Name|Type|Summary|
|----|----|----|
|[Getting EMIT Data using EarthData Search](guides/Getting_EMIT_Data_using_EarthData_Search.md)|Markdown Guide|A thorough walkthrough for using [EarthData Search](https://search.earthdata.nasa.gov/search) to find and download EMIT data|

**Comment by mjami00** [comment]
resolved.
