### ISSUE TITLE
Link to set-up instruction in python/tutorials/GEDI_Finder_Tutorial_Python.ipynb not working

### ISSUE THREAD

**Issue by AntjeUhde** [nasa/GEDI-Data-Resources#22]
Hi,

I was trying to follow the GEDI_Finder_Tutorial_Python.ipynb but the link to the set-up instruction in the "before starting" part is not working. 

Best
Antje

**Comment by amfriesz** [comment]
@AntjeUhde, here's are some [setup instructions](https://github.com/nasa/VITALS/blob/main/setup/setup_instructions.md) that should work. We'll make sure to update the link in the tutorial.
